import { User } from "./user";

export interface MemberProfile {
    user: User;
    middle_name: string | null;
    preferred_name: string;
    date_of_birth: string | null;
    gender: string | null;
    marital_status: string | null;
    nationality: string | null;
    language: string | null;
    occupation: string | null;
    status: string;
    type: string;
    join_date: string | null;
    baptism_date: string | null;
    confirmation_date: string | null;
    membership_class_date: string | null;
    previous_church: string | null;
    email: string | null;
    phone_home: string | null;
    phone_mobile: string | null;
    phone_work: string | null;
    address_street: string | null;
    address_city: string | null;
    address_state: string | null;
    address_postal: string | null;
    address_country: string | null;
    emergency_contact_name: string | null;
    emergency_contact_relationship: string | null;
    emergency_contact_phone: string | null;
    emergency_contact_email: string | null;
    ministry_roles: string[] | null;
    spiritual_gifts: string[] | null;
    skills: string[] | null;
    interests: string[] | null;
    volunteer_preferences: string | null;
    preferred_contact_method: string | null;
    allow_phone_calls: boolean;
    allow_emails: boolean;
    allow_texts: boolean;
    allow_mail: boolean;
    is_private: boolean;
    share_contact_info: boolean;
    share_photos: boolean;
    directory_listed: boolean;
    family_id: string | null;
    family_role: string | null;
    family_notes: string | null;
    photo_url: string | null;
    bio: string | null;
    notes: string | null;
    special_needs: string | null;
    dietary_restrictions: string | null;
    allergies: string | null;
    custom_fields: any | null; // Can be defined more strictly if the structure is known
    tags: string[] | null;
    id: string;
    tenant_id: string;
    member_id: string;
    last_attendance_date: string | null;
    attendance_streak: number;
    total_attendances: number;
    engagement_score: number | null;
    last_contribution_date: string | null;
    last_activity_date: string | null;
    inactive_reason: string | null;
    reactivation_date: string | null;
    last_updated_by_id: string | null;
    last_status_change: string | null;
    status_change_reason: string | null;
    created_at: string;
    updated_at: string | null;
    // Included from previous User model for compatibility if needed
    first_name: string;
    last_name: string;
} 